title: "Home"
description: "Postdoctoral Researcher | Computational Materials Science"
theme: minima

author:
  name: "Rohit Dahule"
  email: "rohitdahule23@gmail.com"

header_pages:
  - research.md
  - publications.md
  - tutorials.md
  - cv.md
  - gallery.md
  - contact.md
